version: '3.8'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    ports:
      - 8000:8000
      - 3000:5000
    depends_on:
      - db
    # volumes:
      # - data:/data

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=libs
    # ports:
    #   - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: